### ISSUE TITLE
This should be a global variable

### ISSUE THREAD

**Issue by chrisdhaan** [Pigpocket/MartiniFinder#1]
https://github.com/Pigpocket/MartiniFinder/blob/4d1d777047ba3e653ce222eea1a4dbf770b657d4/MartiniFinder/Controllers/MapViewController.swift#L125

**Comment by Pigpocket** [comment]
Right. I moved it to my Constants struct in my YelpClient class extension.

**Comment by chrisdhaan** [comment]
Why? Just move it to the top of the MapViewController and make it accessible to the class.

**Comment by Pigpocket** [comment]
Thank you for the suggestion, Chris.
