### ISSUE TITLE
Why are you calling this here and not in the getLocations method? Move it to the getLocations method

### ISSUE THREAD

**Issue by chrisdhaan** [Pigpocket/MartiniFinder#2]
https://github.com/Pigpocket/MartiniFinder/blob/4d1d777047ba3e653ce222eea1a4dbf770b657d4/MartiniFinder/Controllers/MapViewController.swift#L127

**Comment by Pigpocket** [comment]
Done. I was just testing it to see if it works and my print statement gives me the business data.
